@startuml

namespace rclcpp {
  class Node
}

namespace motion_planning {
rclcpp.Node <|-- ObstacleStopPlannerNode
ObstacleStopPlannerNode *-- AdaptiveCruiseController
ObstacleStopPlannerNode *-- ObstacleStopPlannerDebugNode
}

@enduml

@startuml

namespace rclcpp {
  class Node
  class Logger
}

namespace motion_planning {
rclcpp.Node <|-- ObstacleStopPlannerNode
ObstacleStopPlannerNode *-- AdaptiveCruiseController
ObstacleStopPlannerNode *-- ObstacleStopPlannerDebugNode
ObstacleStopPlannerNode *-- ObstaclePointCloud
ObstacleStopPlannerNode *-- VehicleInfo
ObstaclePointCloud *-- VehicleInfo
ObstaclePointCloud *-- rclcpp.Logger
ObstacleStopPlannerNode *-- Trajectory
AdaptiveCruiseController *-- rclcpp.Node
ObstacleStopPlannerDebugNode *-- rclcpp.Node
OneStepPolygon *-- VehicleInfo
PointHelper *-- VehicleInfo


vehicle_info_util.VehicleInfo <|-- VehicleInfo
}
namespace vehicle_info_util {
class VehicleInfo
}

@enduml
