name: Measure code metrics for PR

on:
  pull_request:

env:
  GITHUB_PAGES_URL: https://tier4.github.io/obstacle_stop_planner_refine

jobs:
  code-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variable
        id: set_env
        run: echo "::set-output name=PULL_NUMBER::$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)"

      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Measure code metrics
        run: |
          git clone https://github.com/terryyin/lizard.git
          mkdir -p public/pr-check
          git diff origin/$GITHUB_HEAD_REF..origin/$GITHUB_BASE_REF \
            --diff-filter=AM \
            --name-only -- '*.hpp' '*.cpp' '*.py' > changed_file_list.txt
          python3 lizard/lizard.py -l cpp -l python -x "*test*" -x "*lizard*" -f changed_file_list.txt \
            --CCN 20 -T nloc=200 --arguments 6 \
            --html > public/pr-check/code-metrics.html || true
          python3 lizard/lizard.py -l cpp -l python -x "*test*" -x "*lizard*" -f changed_file_list.txt \
            --CCN 20 -T nloc=200 --arguments 6 || true

      - name: Rename file
        run: |
          mkdir public/pr-check/pr${{ steps.set_env.outputs.PULL_NUMBER }}
          mv public/pr-check/code-metrics.html public/pr-check/pr${{ steps.set_env.outputs.PULL_NUMBER }}/code-metrics.html

      - name: Deploy measurement result page to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true

      - name: Comment PR
        if: ${{ github.event.action == 'opened' }}
        uses: thollander/actions-comment-pull-request@1.0.1
        with:
          message: |
            ### :bar_chart: Code Metrics Report
            Branch  | Metrics
            ------- | -------
            This PR | [code-metrics.html](${{ env.GITHUB_PAGES_URL }}/pr-check/pr${{ steps.set_env.outputs.PULL_NUMBER }}/code-metrics.html)
            main    | [code-metrics.html](${{ env.GITHUB_PAGES_URL }}/pr-check/main/code-metrics.html)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-index-page:
    needs: code-metrics
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Create index page
        run: |
          cd pr-check
          tree -H "$GITHUB_PAGES_URL/pr-check" \
            -L 2 --noreport --charset utf-8 -T 'Index of code metrics' \
            -P "*.html" > index.html

      - name: git setting
        run: |
          git config --local user.email "actions@example.com"
          git config --local user.name "Github Actions"

      - name: Commit file
        run: |
          git add pr-check/index.html
          git commit -m "Add index.html" --allow-empty
          git push origin gh-pages
