name: Comment code metrics report to PR

on:
  pull_request:
    types: [opened]

jobs:
  comment-report:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        id: plum
        run: echo "::set-output name=PULL_NUMBER::$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        needs: code-metrics
        with:
          message: |
            A code metrics report for this pull request has been generated. You can see the result [here](https://tier4.github.io/obstacle_stop_planner_refine/pr-check/pr${{ steps.plum.outputs.PULL_NUMBER }}/code-metrics.html).
            Click [here](https://tier4.github.io/obstacle_stop_planner_refine/pr-check/main/code-metrics.html) for the main branch metrics report.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
