name: Comment code metrics report to PR

on:
  pull_request:
    types: [opened]

jobs:
  comment-report:
    needs: code-metrics
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        id: plum
        run: echo "::set-output name=PULL_NUMBER::$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: |
            ### :bar_chart: Code Metrics Report
            Branch | Metrics
            ------------ | -------------
            This PR | [code-metrics.html](https://tier4.github.io/obstacle_stop_planner_refine/pr-check/pr${{ steps.plum.outputs.PULL_NUMBER }}/code-metrics.html)
            main | [code-metrics.html](https://tier4.github.io/obstacle_stop_planner_refine/pr-check/main/code-metrics.html)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
