name: Deploy MkDocs to gh-pages

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variable
        id: set_env
        run: echo "::set-output name=PULL_NUMBER::$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Build MkDocs
        run: |
          python -m pip install --upgrade pip setuptools wheel
          scripts/install_mkdocs.sh
          mkdocs build -f mkdocs.yml --verbose --clean

      - name: Change directory structure
        run: |
          mkdir -p public/pr-check/pr${{ steps.set_env.outputs.PULL_NUMBER }}
          mv site public/pr-check/pr${{ steps.set_env.outputs.PULL_NUMBER }}/

      - name: Deploy MkDocs to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
