name: Deploy MkDocs to gh-pages

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        id: plum
        run: echo "::set-output name=PULL_NUMBER::$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build MkDocs
        uses: jnanadarshan/mkdocs-build-action@v1

      - name: Change directory structure
        run: |
          mkdir -p public/pr-check/pr${{ steps.plum.outputs.PULL_NUMBER }}
          mv site public/pr-check/pr${{ steps.plum.outputs.PULL_NUMBER }}/

      - name: Deploy MkDocs to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
