name: Clang nightly build

on:
  schedule:
    - cron: "0 19 * * *" # run at 4 AM JST
  workflow_dispatch:

jobs:
  build-using-clang:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - foxy
          - galactic
          - rolling

        include:
          # Foxy Fitzroy (June 2020 - May 2023)
          - docker_image: ubuntu:focal
            ros_distribution: foxy

          # Galactic Geochelone (May 2021 - November 2022)
          - docker_image: ubuntu:focal
            ros_distribution: galactic

          # Rolling Ridley (June 2020 -)
          - docker_image: ubuntu:focal
            ros_distribution: rolling

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Search packages in this repository
        id: list_packages
        run: |
          echo ::set-output name=package_list::$(colcon list --names-only)

      - name: Run action-ros-ci
        id: action_ros_ci_step
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: ${{ steps.list_packages.outputs.package_list }}
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: build_depends.repos
          import-token: ${{ secrets.REPO_TOKEN }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["release", "compile-commands"],
                "cmake-args": [
                  "-DCMAKE_C_COMPILER=clang",
                  "-DCMAKE_CXX_COMPILER=clang++",
                  "-DCMAKE_CXX_FLAGS='-Wthread-safety'",
                  "-DFORCE_BUILD_VENDOR_PKG=ON"
                ],
                "continue-on-error": true
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/1ddb69bedfd1f04c2f000e95452f7c24a4d6176b/index.yaml
